### ISSUE TITLE
Enhancement: expose line number information

### ISSUE THREAD

**Issue by MathieuDuponchelle** [pwithnall/dbus-deviation#3]
I'd like to be able to link to the exact place a symbol is defined, clang exposes this information through node.location.lineno, node.location.filename for example, arguably the filename is always known in the dbus case so a simple node.lineno would be enough.

Slightly related, is there a reason for not having all the symbol types inherit from a base node class (which could conveniently have a comment attribute as well) ?

And usually abstract syntax trees can be walked with generic methods, which is useful for certain purposes, so having that base class expose node.children might be something to consider ?

**Comment by pwithnall** [comment]
> I'd like to be able to link to the exact place a symbol is defined, clang exposes this information through node.location.lineno, node.location.filename for example, arguably the filename is always known in the dbus case so a simple node.lineno would be enough.

Definitely. I didn’t do this before because `xml.etree` does not support it — but [`lxml` does](http://lxml.de/api/lxml.etree._Element-class.html#sourceline), which is excellent. Patches welcome.

As well as the `sourceline`, it might also make sense to expose the XPath of the symbol’s element in the XML too. (I’m thinking of the case here where the introspection XML file we’re parsing is all one one line because it’s machine generated.)

> Slightly related, is there a reason for not having all the symbol types inherit from a base node class (which could conveniently have a comment attribute as well) ?

Because there’s nothing common between them which can’t be exposed as an interface.

> And usually abstract syntax trees can be walked with generic methods, which is useful for certain purposes, so having that base class expose node.children might be something to consider ?

What’s the use case? Probably best to open a new issue to discuss this one. I’m not opposed to adding a `Container` interface or something for navigating down the hierarchy, but would like to know the use case so we get it right.
